module.exports = {
  someSidebar: {
    "Getting Started": [
        'index',
        'setup',
        'dashboard',
        'privacy',
    ],
    Features: [
        'alias',
        'announce',
        'badwords',
        'ban',
        'blacklist',
        'captcha',
        'check',
        'config',
        'echo',
        'enable',
        'feedback',
        'gate',
        'get',
        'help',
        'kick',
        'invite',
        'leave',
        'motd',
        'mute',
        'notes',
        'pin',
        'reloads',
        'report',
        'rm',
        'rules',
        'safegroups',
        'start',
        'status',
        'support',
        'test',
        'trust',
        'welcome',
    ],
    Contribute: [
        'bug',
        'feature',
        'translate',
    ],
  },
};
